version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  build_and_push_caris_caller_image:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          create-repo: false
          dockerfile: ./carisbatch/Dockerfile
          path: ./carisbatch/
          region: AWS_REGION_ENV_VAR_NAME
          repo: callcarisbatch
          tag: "caris_caller_image-latest"

  build_and_push_startstopec2_image:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          create-repo: false
          dockerfile: ./startstopec2/Dockerfile
          path: ./startstopec2/
          region: AWS_REGION_ENV_VAR_NAME
          repo: callcarisbatch
          tag: "startstopec2_image-latest"
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          create-repo: false
          dockerfile: ./mbsystem/Dockerfile
          path: ./mbsystem/
          region: AWS_REGION_ENV_VAR_NAME
          repo: "ausseabed-mbsystem"
          tag: "latest"
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          create-repo: false
          dockerfile: ./pdal/Dockerfile
          path: ./pdal/
          region: AWS_REGION_ENV_VAR_NAME
          repo: "ausseabed-pdal"
          tag: "latest"

  build_and_push_gdal_image:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          create-repo: false
          dockerfile: ./gdal/Dockerfile
          path: ./gdal/
          region: AWS_REGION_ENV_VAR_NAME
          repo: "ausseabed-gdal"
          tag: "latest"

workflows:
  update_infra_and_application:
    jobs:
      - build_and_push_caris_caller_image:
          filters:
            branches:
              only:
                - master
      - build_and_push_startstopec2_image:
          filters:
            branches:
              only:
                - master
      - build_and_push_gdal_image:
          filters:
            branches:
              only:
                - master
                - /.*NGA-383.*/
