version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.0.0

jobs:
  build_and_push_caris_caller_image:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/ecr-login:
          region: ${AWS_REGION_ENV_VAR_NAME}
      - aws-ecr/build-image:
          path: ./carisbatch
          region: ${AWS_REGION_ENV_VAR_NAME}
          repo: callcarisbatch
          tag: "caris_caller_image-latest"

  build_and_push_startstopec2_image:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/ecr-login:
          region: ${AWS_REGION_ENV_VAR_NAME}
      - aws-ecr/build-image:
          path: ./startstopec2
          region: ${AWS_REGION_ENV_VAR_NAME}
          repo: callcarisbatch
          tag: "startstopec2_image-latest"

  build_and_push_mbsystem_image:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/ecr-login:
          region: ${AWS_REGION_ENV_VAR_NAME}
      - aws-ecr/build-image:
          path: ./mbsystem
          region: ${AWS_REGION_ENV_VAR_NAME}
          repo: "ausseabed-mbsystem"
          tag: "latest"

  build_and_push_pdal_image:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/ecr-login:
          region: ${AWS_REGION_ENV_VAR_NAME}
      - aws-ecr/build-image:
          path: ./pdal
          region: ${AWS_REGION_ENV_VAR_NAME}
          repo: "ausseabed-pdal"
          tag: "latest"

  build_and_push_gdal_image:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/ecr-login:
          region: ${AWS_REGION_ENV_VAR_NAME}
      - aws-ecr/build-image:
          path: ./gdal
          region: ${AWS_REGION_ENV_VAR_NAME}
          repo: "ausseabed-gdal"
          tag: "latest"

  build_and_push_surveyzip_image:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - run: mvn -f ./surveyzip/pom.xml clean package
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/ecr-login:
          region: ${AWS_REGION_ENV_VAR_NAME}
      - aws-ecr/build-image:
          path: ./surveyzip
          region: ${AWS_REGION_ENV_VAR_NAME}
          repo: "ausseabed-surveyzip"
          tag: "latest"

workflows:
  update_infra_and_application:
    jobs:
      - build_and_push_caris_caller_image:
          filters:
            branches:
              only:
                - master
      - build_and_push_startstopec2_image:
          filters:
            branches:
              only:
                - master
      - build_and_push_mbsystem_image:
          filters:
            branches:
              only:
                - master
      - build_and_push_pdal_image:
          filters:
            branches:
              only:
                - master
      - build_and_push_gdal_image:
          filters:
            branches:
              only:
                - master
                - /.*NGA-383.*/
      - build_and_push_surveyzip_image:
          filters:
            branches:
              only:
                - master