version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/asf
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: check s3
          command: aws sts get-caller-identity
      - run:
          name: Install terraform
          command: wget https://releases.hashicorp.com/terraform/0.12.17/terraform_0.12.17_linux_amd64.zip && unzip terraform_0.12.17_linux_amd64.zip && chmod +x terraform && sudo mv terraform /usr/bin/
      - run:
          name: terraform init
          working_directory: ~/asf/infra
          command: terraform init
      - run:
          name: terraform plan
          working_directory: ~/asf/infra
          command: terraform plan
      
    

workflows:
  terraform_test:
    jobs:
      - deploy
  # build_and_push_image:
  #   jobs:
  #     - aws-ecr/build-and-push-image:
  #         account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
  #         aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
  #         aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
  #         create-repo: false
  #         dockerfile: ./carisbatch/Dockerfile
  #         path: ./carisbatch/
  #         region: AWS_REGION_ENV_VAR_NAME
  #         repo: callcarisbatch
  #         tag: 'caris_caller_image-latest'
  #     - aws-ecr/build-and-push-image:
  #         account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
  #         aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
  #         aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
  #         create-repo: false
  #         dockerfile: ./startstopec2/Dockerfile
  #         path: ./startstopec2/
  #         region: AWS_REGION_ENV_VAR_NAME
  #         repo: callcarisbatch
  #         tag: 'startstopec2_image-latest'
